keys:
  - cipher: chacha20-ietf-poly1305
    id: '1'
    port: 3987
    secret: nyPCQxQNnxGaMrgXczawir
  - cipher: chacha20-ietf-poly1305
    id: '2'
    port: 3987
    secret: m42DgdChCH535qJFeecjfo
  - cipher: chacha20-ietf-poly1305
    id: '3'
    port: 3987
    secret: rDVfHdQhEPuy0mIvksEQsX
  - cipher: chacha20-ietf-poly1305
    id: '8'
    port: 3987
    secret: 8zxCw5EFJXtYRPVSkXkAXE
  - cipher: chacha20-ietf-poly1305
    id: '9'
    port: 3987
    secret: sb3pxk1tnS38XoWFKYlFnZ
  - cipher: chacha20-ietf-poly1305
    id: '10'
    port: 3987
    secret: aFMW4yK8hXt5YZ2FlHcp79
  - cipher: chacha20-ietf-poly1305
    id: '11'
    port: 3987
    secret: 8teTo88NnQXwBiFgh1Y0UE
  - cipher: chacha20-ietf-poly1305
    id: '12'
    port: 3987
    secret: BPYJRXksZwBoF1CzPAkAlP
  - cipher: chacha20-ietf-poly1305
    id: '14'
    port: 3987
    secret: P1JmO99rCLLBOY8xa7K8jS
  - cipher: chacha20-ietf-poly1305
    id: '15'
    port: 3987
    secret: Ea6P5spL4AskbW6eL2bpkK
  - cipher: chacha20-ietf-poly1305
    id: '16'
    port: 3987
    secret: HZM3WNrFdSWUUgbmqmGTJU
  - cipher: chacha20-ietf-poly1305
    id: '17'
    port: 3987
    secret: pantotmbmnPCasfWv22NrC
  - cipher: chacha20-ietf-poly1305
    id: '19'
    port: 3987
    secret: eJdyX9FYzglmQvv4zPhwNy
  - cipher: chacha20-ietf-poly1305
    id: '20'
    port: 3987
    secret: dBbMl8CP5KhP7PxL62JDyf
  - cipher: chacha20-ietf-poly1305
    id: '21'
    port: 3987
    secret: mgHuNUknziu6GUZZryArsP
  - cipher: chacha20-ietf-poly1305
    id: '22'
    port: 3987
    secret: NyCOPfdx5uvWniVhZYDaXU
  - cipher: chacha20-ietf-poly1305
    id: '23'
    port: 3987
    secret: kDnolpSTc5E8dfx7Gtpiln
  - cipher: chacha20-ietf-poly1305
    id: '24'
    port: 3987
    secret: jlUI9s2gRusv4qRxBK5fEh
  - cipher: chacha20-ietf-poly1305
    id: '26'
    port: 3987
    secret: c4FWuMmviguYEHIwefL9ni
  - cipher: chacha20-ietf-poly1305
    id: '27'
    port: 3987
    secret: MWMdXbdFDF6FCZEOrdJ2tK
  - cipher: chacha20-ietf-poly1305
    id: '28'
    port: 3987
    secret: sFEDbLotPreUwvEvLZs4oO
  - cipher: chacha20-ietf-poly1305
    id: '29'
    port: 3987
    secret: tetUqIPPTo2lJX8pueUB0i
  - cipher: chacha20-ietf-poly1305
    id: '30'
    port: 3987
    secret: TMo7ZcPvGaZGl0SuLvPXvk
  - cipher: chacha20-ietf-poly1305
    id: '31'
    port: 3987
    secret: vF4ygdAkGU1HDlyUTC2eAv
  - cipher: chacha20-ietf-poly1305
    id: '32'
    port: 3987
    secret: L9FUtVZm8uEXk0M28hrYan
  - cipher: chacha20-ietf-poly1305
    id: '33'
    port: 3987
    secret: j8Af46A9F0Z6kfu1dmg0oe
  - cipher: chacha20-ietf-poly1305
    id: '35'
    port: 3987
    secret: bWjLaVWJKQSo16KQQKCDbr
  - cipher: chacha20-ietf-poly1305
    id: '36'
    port: 3987
    secret: 3hONvrQd597ilOp0XfLIoB
  - cipher: chacha20-ietf-poly1305
    id: '37'
    port: 3987
    secret: FbwC4geuBvN08vfu5jaFxE
  - cipher: chacha20-ietf-poly1305
    id: '38'
    port: 3987
    secret: ftNvUYVpzLWw1uxbRfbpN0
  - cipher: chacha20-ietf-poly1305
    id: '39'
    port: 3987
    secret: OFbdQcyO5PnVHCzNBjITnY
  - cipher: chacha20-ietf-poly1305
    id: '40'
    port: 3987
    secret: bFKDXPMoXUcg1QumdQSHVC
  - cipher: chacha20-ietf-poly1305
    id: '41'
    port: 3987
    secret: 6oDUACmhEylSlV7wolROIY
  - cipher: chacha20-ietf-poly1305
    id: '42'
    port: 3987
    secret: SLbJFRrxxwQoUAaHN4LjoQ
  - cipher: chacha20-ietf-poly1305
    id: '43'
    port: 3987
    secret: la6K4fSgfMkZtURqIBaLT4
  - cipher: chacha20-ietf-poly1305
    id: '44'
    port: 3987
    secret: QExQWYvQw6kkZz4q2Ppnjp
  - cipher: chacha20-ietf-poly1305
    id: '45'
    port: 3987
    secret: TLbywizvePXwVykCQCQXa8
  - cipher: chacha20-ietf-poly1305
    id: '46'
    port: 3987
    secret: sFhTGqoHF19wPdCYsZyKUD
  - cipher: chacha20-ietf-poly1305
    id: '47'
    port: 3987
    secret: TphYPutqOH85AOMaFS86Gi
  - cipher: chacha20-ietf-poly1305
    id: '48'
    port: 3987
    secret: R1Zuccd5tGkf1fMnNL9n07
  - cipher: chacha20-ietf-poly1305
    id: '49'
    port: 3987
    secret: FGWIFnQkLtrmhYZLy0k8tC
  - cipher: chacha20-ietf-poly1305
    id: '50'
    port: 3987
    secret: 6bcdKTxWhrrD93tCmZBd9e
  - cipher: chacha20-ietf-poly1305
    id: '51'
    port: 44526
    secret: 2aK5f4e3BQcsIEL3F4aVmK
